name: Deploy to Production

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build Android Production
        run: eas build --platform android --profile production --non-interactive

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: |
            ## 🚀 TallyKhata Production Release
            
            ### What's New
            - Production build with latest features
            - Optimized performance and stability
            - Enhanced security measures
            
            ### Build Details
            - Version: ${{ github.ref_name }}
            - Commit: ${{ github.sha }}
            - Date: ${{ github.event.head_commit.timestamp }}
            
            ### Download
            Build artifacts are available in the EAS dashboard.
